refactor: include migration abort on PID

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/init-postgres-config/conf.d/015-migration b/rootfs/etc/s6-overlay/s6-rc.d/init-postgres-config/conf.d/015-migration
--- a/rootfs/etc/s6-overlay/s6-rc.d/init-postgres-config/conf.d/015-migration
+++ b/rootfs/etc/s6-overlay/s6-rc.d/init-postgres-config/conf.d/015-migration
@@ -17,6 +17,11 @@ if [[ -n ${PG_OLD_VERSION} ]]; then
     # Enable migration
     PG_OLD_VERSION_MAJOR=$(echo "${PG_OLD_VERSION}" | cut -d '.' -f 1)
 
+    if [ -f "${PG_OLD_DATADIR}/main/postmaster.pid" ]; then
+      log-init "postmaster.pid detected in previous data directory; ABORTING"
+      exit 1
+    fi
+
     log-init "entering migration mode"
     env_set PG_MIGRATION 1
     env_set PG_OLD_VERSION "${PG_OLD_VERSION}"
