fix: psql-backup return codes

diff --git a/rootfs/usr/bin/psql-backup b/rootfs/usr/bin/psql-backup
--- a/rootfs/usr/bin/psql-backup
+++ b/rootfs/usr/bin/psql-backup
@@ -83,16 +83,17 @@ log-init "backing up data on $REPLICATION_HOST..."
 s6-setuidgid abc exec env PGPASSWORD="${REPLICATION_PASS}" pg_basebackup "${PARAMS[@]}"; BACKUP_STATUS=$?
 
 case $BACKUP_STATUS in
-  50)
+  0)
     log-init "backup of ${REPLICATION_HOST} completed"
+    exit 50
   ;;
-  51)
+  *)
     log-init "backup of ${REPLICATION_HOST} failed; see log file"
     if is_enabled "${PG_BACKUP_REMOVE_DATA_ON_FAILURE}"; then
       rm -R "${PG_DATA_DIR:?}/"*
     fi
+
+    # Return backup exit code
+    exit ${BACKUP_STATUS}
   ;;
 esac
-
-# Return backup exit code
-exit ${BACKUP_STATUS}
