fix: psql backup

diff --git a/rootfs/etc/cont-init.d/15-config b/rootfs/etc/cont-init.d/15-config
--- a/rootfs/etc/cont-init.d/15-config
+++ b/rootfs/etc/cont-init.d/15-config
@@ -59,6 +59,7 @@ chmod -R 0755 "${PG_RUN_DIR}"
 chmod g+s "${PG_RUN_DIR}"
 chown -R abc:abc "${PG_RUN_DIR}"
 
+
 ################################################################################
 # Certificates
 if [ ! -d "${PG_CERTS_DIR}" ]; then
@@ -68,65 +69,90 @@ else
 	log-init "directory::certs exists [${PG_CERTS_DIR}]"
 fi
 
+
+################################################################################
+# Verify SSL/TLS
+if is_enabled "${PG_SSL}"; then
+	log-init "SSL/TLS: Enabled"
+
+	if [ ! -f "${PG_CERTS_DIR}/server.crt" ]; then
+		log-init "ERROR: SSL/TLS is enabled certificate not found [${PG_CERTS_DIR}/server.crt]"
+		exit 41
+	else
+		if [ "$(stat -c "%a" "${PG_CERTS_DIR}/server.crt")" != "644" ]; then
+			log-init "invalid permissions for ${PG_CERTS_DIR}/server.crt; expect: 644"
+			exit 42
+		fi
+	fi
+
+	if [ ! -f "${PG_CERTS_DIR}/server.key" ]; then
+		log-init "ERROR: SSL/TLS is enabled certificate key not found [${PG_CERTS_DIR}/server.key]"
+		exit 43
+	else
+		if [ "$(stat -c "%a" "${PG_CERTS_DIR}/server.key")" != "640" ]; then
+			log-init "invalid permissions for ${PG_CERTS_DIR}/server.key; expect: 640"
+			exit 44
+		fi
+	fi
+fi
+
 # set permissions on PG_CERTS_DIR
 chown abc:abc "${PG_CERTS_DIR}"
-
-
-################################################################################
-# Create Database init.d for custom load scripts
-if [ ! -d "${PG_INIT_DB}" ]; then
-	log-init "creating directory::init.db.d [${PG_INIT_DB}]"
-	mkdir -p "${PG_INIT_DB}"
-fi
-
-# Set permissions on PG_INIT_DB
-log-init "setting permissions::init.db.d"
-chown -R abc:abc "${PG_INIT_DB}"
-
-
-################################################################################
-# validate Configuration
-if [ "$PG_PASS" == "postgres" ]; then
-  log-init "WARNING: postgres user password still set to default; only use this for test/dev environments"
-fi
-
-case ${REPLICATION_MODE,,} in
-	slave|snapshot|backup) ;;
-	*)
-		if [[ -z ${DB_USER} ]]; then
-			log-init "ERROR: required variable DB_USER not set"
-			exit 15
-		fi
-
-		if [[ -z ${DB_PASS} ]]; then
-			log-init "ERROR: required variable DB_PASS not set"
-			exit 16
-		fi
-
-		if [[ -z ${DB_NAME} ]]; then
-			log-init "ERROR: required variable DB_NAME not set"
-			exit 17
-		fi
-	;;
-esac
 
 if [[ ! -f ${PG_DATA_DIR}/PG_VERSION ]]; then
 	case ${REPLICATION_MODE,,} in
 		slave|snapshot|backup)
-		if [[ -z $REPLICATION_HOST ]]; then
-			log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_HOST not set"
-			exit 18
-		fi
+			if [[ -z $REPLICATION_HOST ]]; then
+				log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_HOST not set"
+				exit 18
+			fi
 
-		if [[ -z $REPLICATION_USER ]]; then
-			log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_USER not set"
-			exit 19
-		fi
+			if [[ -z $REPLICATION_USER ]]; then
+				log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_USER not set"
+				exit 19
+			fi
 
-		if [[ -z $REPLICATION_PASS ]]; then
-			echo "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_PASS not set"
-			exit 20
-		fi
+			if [[ -z $REPLICATION_PASS ]]; then
+				echo "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_PASS not set"
+				exit 20
+			fi
+		;;
+
+		*)
+			################################################################################
+			# Create Database init.d for custom load scripts
+			if [ ! -d "${PG_INIT_DB}" ]; then
+				log-init "creating directory::init.db.d [${PG_INIT_DB}]"
+				mkdir -p "${PG_INIT_DB}"
+			fi
+
+			# Set permissions on PG_INIT_DB
+			log-init "setting permissions::init.db.d"
+			chown -R abc:abc "${PG_INIT_DB}"
+
+
+			################################################################################
+			# validate Configuration
+			if [ "$PG_PASS" == "postgres" ]; then
+				log-init "WARNING: postgres user password still set to default; only use this for test/dev environments"
+			fi
+
+			if [[ -z ${DB_USER} ]]; then
+				log-init "ERROR: required variable DB_USER not set"
+				exit 15
+			fi
+
+			if [[ -z ${DB_PASS} ]]; then
+				log-init "ERROR: required variable DB_PASS not set"
+				exit 16
+			fi
+
+			if [[ -z ${DB_NAME} ]]; then
+				log-init "ERROR: required variable DB_NAME not set"
+				exit 17
+			fi
+		;;
+
 	esac
 fi
 
diff --git a/rootfs/etc/cont-init.d/20-db-init b/rootfs/etc/cont-init.d/20-db-init
--- a/rootfs/etc/cont-init.d/20-db-init
+++ b/rootfs/etc/cont-init.d/20-db-init
@@ -28,16 +28,20 @@ if [[ ! -f ${PG_DATA_DIR}/PG_VERSION ]]; then
 
 			backup)
 				log-init "backing up data on $REPLICATION_HOST..."
-				s6-setuidgid abc exec env PGPASSWORD="${REPLICATION_PASS}" pg_basebackup -D "${PG_DATA_DIR}" \
-					-h "${REPLICATION_HOST}" -p "${REPLICATION_PORT}" -U "${REPLICATION_USER}" -X fetch -w -P
-				log-init "backup of ${REPLICATION_HOST} completed"
-				log-init "syncing disks"
-				s6-sync
+				psql-backup; BACKUP_STATUS=$?
+				case $BACKUP_STATUS in
+					50)
+						log-init "backup of ${REPLICATION_HOST} completed"
+					;;
+					51)
+						log-init "backup of ${REPLICATION_HOST} failed; see log file"
+					;;
+					52)
+						log-init "invalid option for PG_BACKUP_FORMAT; valid options are p|plain|t|tar"
+					;;
+				esac
 
-				exit 50
-
-				# Gracefull terminate container
-				kill -s SIGTERM 1
+				exit ${BACKUP_STATUS}
 			;;
 		esac
 	;;
