fix: validation for non backups

diff --git a/rootfs/etc/cont-init.d/15-config b/rootfs/etc/cont-init.d/15-config
--- a/rootfs/etc/cont-init.d/15-config
+++ b/rootfs/etc/cont-init.d/15-config
@@ -101,22 +101,7 @@ chown abc:abc "${PG_CERTS_DIR}"
 
 if [[ ! -f ${PG_DATA_DIR}/PG_VERSION ]]; then
 	case ${REPLICATION_MODE,,} in
-		slave|snapshot|backup)
-			if [[ -z $REPLICATION_HOST ]]; then
-				log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_HOST not set"
-				exit 18
-			fi
-
-			if [[ -z $REPLICATION_USER ]]; then
-				log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_USER not set"
-				exit 19
-			fi
-
-			if [[ -z $REPLICATION_PASS ]]; then
-				echo "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_PASS not set"
-				exit 20
-			fi
-		;;
+		backup) ;;
 
 		*)
 			################################################################################
@@ -152,7 +137,27 @@ if [[ ! -f ${PG_DATA_DIR}/PG_VERSION ]]; then
 				exit 17
 			fi
 		;;
+	esac
+fi
 
+if [[ ! -f ${PG_DATA_DIR}/PG_VERSION ]]; then
+	case ${REPLICATION_MODE,,} in
+		slave|snapshot|backup)
+			if [[ -z $REPLICATION_HOST ]]; then
+				log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_HOST not set"
+				exit 18
+			fi
+
+			if [[ -z $REPLICATION_USER ]]; then
+				log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_USER not set"
+				exit 19
+			fi
+
+			if [[ -z $REPLICATION_PASS ]]; then
+				echo "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_PASS not set"
+				exit 20
+			fi
+		;;
 	esac
 fi
 
