fix: migration process

diff --git a/rootfs/etc/cont-init.d/20-db-init b/rootfs/etc/cont-init.d/20-db-init
--- a/rootfs/etc/cont-init.d/20-db-init
+++ b/rootfs/etc/cont-init.d/20-db-init
@@ -103,8 +103,10 @@ if ! psql_is_initialized; then
           PG_OLD_USRLIB=${PG_OLD_ROOTFS}/usr/lib
           PG_OLD_BINDIR=${PG_OLD_ROOTFS}/usr/bin
         else
-          log-init "installing previous PostgreSQL ${PG_OLD_VERSION_MAJOR}"
-          apk add --update --no-cache "postgresql${PG_OLD_VERSION_MAJOR}" "postgresql${PG_OLD_VERSION_MAJOR}-client"
+          log-init "os: updating package indexes"
+          apk update > /dev/null 2>&1
+          log-init "os: installing previous PostgreSQL ${PG_OLD_VERSION_MAJOR}"
+          apk add --no-cache "postgresql${PG_OLD_VERSION_MAJOR}" "postgresql${PG_OLD_VERSION_MAJOR}-client"
 
           PG_OLD_USRLIB="/usr/lib/postgresql${PG_OLD_VERSION_MAJOR}"
           PG_OLD_BINDIR="/usr/libexec/postgresql${PG_OLD_VERSION_MAJOR}"
@@ -126,15 +128,21 @@ if ! psql_is_initialized; then
         PG_UPGRADE_PARAMS+=(--old-options="-c config_file=${PG_OLD_CONF} --hba_file=${PG_OLD_HBA_CONF} --ident_file=${PG_OLD_IDENT_CONF}")
         PG_UPGRADE_PARAMS+=(--new-options="-c config_file=${PG_CONF} --hba_file=${PG_HBA_CONF} --ident_file=${PG_IDENT_CONF}")
 
-        echo -n "  migration in progress. Please be patient..."
+        log-init "starting migration. Please be patient"
         if (( "${PG_OLD_VERSION_MAJOR}" < 12 )); then
           PG_LIB_PATH="${PG_OLD_LIB}:${PG_OLD_USRLIB}:/lib:/usr/local/lib:/usr/lib"
         else
           PG_LIB_PATH="${PG_OLD_USRLIB}:/lib:/usr/local/lib:/usr/lib"
         fi
         cd "${PG_HOME}"
-        # TODO: Handle error of pg_upgrade
-        s6-setuidgid abc exec env LD_LIBRARY_PATH="${PG_LIB_PATH}" pg_upgrade "${PG_UPGRADE_PARAMS[@]}" > "${PG_LOG_DIR}/pg_upgrade-v${PG_OLD_VERSION}-v${PG_VERSION_SLUG}.log"
+        if s6-setuidgid abc stdbuf -o0 exec env LD_LIBRARY_PATH="${PG_LIB_PATH}" pg_upgrade "${PG_UPGRADE_PARAMS[@]}" 2>&1 | stdbuf -i0 -o0 tee "${PG_LOG_DIR}/pg_upgrade-v${PG_OLD_VERSION}-v${PG_VERSION_SLUG}.log"; then
+          log-init "migration succesful"
+          env_set PG_MIGRATION_SUCCESS 1
+        else
+          log-init "migration failed"
+          env_set PG_MIGRATION_SUCCESS 0
+          exit 62
+        fi
       fi
     ;;
   esac
