fix: update init scripts

diff --git a/rootfs/etc/cont-init.d/20-db-init b/rootfs/etc/cont-init.d/20-db-init
--- a/rootfs/etc/cont-init.d/20-db-init
+++ b/rootfs/etc/cont-init.d/20-db-init
@@ -9,81 +9,82 @@ source /etc/postgresql/functions
 
 
 if [[ ! -f ${PG_DATA_DIR}/PG_VERSION ]]; then
-	case ${REPLICATION_MODE,,} in slave|snapshot|backup)
-		# Wait for master to be ready
-		is_master_ready
+	case ${REPLICATION_MODE,,} in
+		slave|snapshot|backup)
+			# Wait for master to be ready
+			is_master_ready
 
-		case ${REPLICATION_MODE,,} in
-			slave)
-				log-init "replicating initial data from ${REPLICATION_HOST}..."
-				s6-setuidgid abc exec env PGPASSWORD="${REPLICATION_PASS}" pg_basebackup -D "${PG_DATA_DIR}" \
-					-h "${REPLICATION_HOST}" -p "${REPLICATION_PORT}" -U "${REPLICATION_USER}" -X stream -w >/dev/null
-			;;
+			case ${REPLICATION_MODE,,} in
+				slave)
+					log-init "replicating initial data from ${REPLICATION_HOST}..."
+					s6-setuidgid abc exec env PGPASSWORD="${REPLICATION_PASS}" pg_basebackup -D "${PG_DATA_DIR}" \
+						-h "${REPLICATION_HOST}" -p "${REPLICATION_PORT}" -U "${REPLICATION_USER}" -X stream -w >/dev/null
+				;;
 
-			snapshot)
-				psql-snapshot
-			;;
+				snapshot)
+					psql-snapshot
+				;;
 
-			backup)
-				psql-backup
-			;;
-		esac
-	;;
+				backup)
+					psql-backup
+				;;
+			esac
+		;;
 
-	*)
-		log-init "initializing database..."
-		PG_OLD_VERSION=$(find "${PG_HOME}"/[0-9][0-9].[0-9]/main -maxdepth 1 -name PG_VERSION 2>/dev/null | grep -v "${PG_VERSION}" | sort -r | head -n1 | cut -d'/' -f5)
-		if [[ -n ${PG_OLD_VERSION} ]]; then
-			log-init "migrating PostgreSQL ${PG_OLD_VERSION} data to ${PG_VERSION}..."
+		*)
+			log-init "initializing database..."
+			PG_OLD_VERSION=$(find "${PG_HOME}"/[0-9][0-9].[0-9]/main -maxdepth 1 -name PG_VERSION 2>/dev/null | grep -v "${PG_VERSION}" | sort -r | head -n1 | cut -d'/' -f5)
+			if [[ -n ${PG_OLD_VERSION} ]]; then
+				log-init "migrating PostgreSQL ${PG_OLD_VERSION} data to ${PG_VERSION}..."
 
-			# TODO: Diskspace check
+				# TODO: Diskspace check
 
-			# protect the existing data from being altered by apt-get
-			mv "${PG_HOME}/${PG_OLD_VERSION}" "${PG_HOME}/${PG_OLD_VERSION}.migrating"
+				# protect the existing data from being altered by apt-get
+				mv "${PG_HOME}/${PG_OLD_VERSION}" "${PG_HOME}/${PG_OLD_VERSION}.migrating"
 
-			log-init "installing PostgreSQL ${PG_OLD_VERSION}..."
-			if ! ( apk add --update --no-cache postgresql="${PG_OLD_VERSION}" postgresql-client="${PG_OLD_VERSION}" ) >/dev/null; then
-				log-init "ERROR: Failed to install PostgreSQL ${PG_OLD_VERSION}. Restoring data..."
+				log-init "installing PostgreSQL ${PG_OLD_VERSION}..."
+				if ! ( apk add --update --no-cache postgresql="${PG_OLD_VERSION}" postgresql-client="${PG_OLD_VERSION}" ) >/dev/null; then
+					log-init "ERROR: Failed to install PostgreSQL ${PG_OLD_VERSION}. Restoring data..."
 
-				# First move the old data back
+					# First move the old data back
+					rm -rf "${PG_HOME}/${PG_OLD_VERSION:?}"
+					mv "${PG_HOME}/${PG_OLD_VERSION}.migrating" "${PG_HOME}/${PG_OLD_VERSION}"
+					log-init "data Restore Succesful. Exiting..."
+					exit 10
+				fi
+
+				# we're ready to migrate, move back the old data and remove the trap
 				rm -rf "${PG_HOME}/${PG_OLD_VERSION:?}"
 				mv "${PG_HOME}/${PG_OLD_VERSION}.migrating" "${PG_HOME}/${PG_OLD_VERSION}"
-				log-init "data Restore Succesful. Exiting..."
-				exit 10
 			fi
 
-			# we're ready to migrate, move back the old data and remove the trap
-			rm -rf "${PG_HOME}/${PG_OLD_VERSION:?}"
-			mv "${PG_HOME}/${PG_OLD_VERSION}.migrating" "${PG_HOME}/${PG_OLD_VERSION}"
-		fi
+			if [[ -n ${PG_PASS} ]]; then
+				echo "${PG_PASS}" > /tmp/pwfile
+			fi
 
-		if [[ -n ${PG_PASS} ]]; then
-			echo "${PG_PASS}" > /tmp/pwfile
-		fi
-
-		s6-setuidgid abc initdb \
-			--pgdata="${PG_DATA_DIR}" \
-			--username="${PG_USER}" \
-			--locale="${LANG}" \
-			--encoding=unicode \
-			--auth=trust ${PG_PASS:+--pwfile=/tmp/pwfile} >/dev/null
-
-		if [[ -n ${PG_OLD_VERSION} ]]; then
-			PG_OLD_DATADIR=${PG_HOME}/${PG_OLD_VERSION}/main
-			PG_OLD_CONF=${PG_OLD_DATADIR}/postgresql.conf
-			PG_OLD_HBA_CONF=${PG_OLD_DATADIR}/pg_hba.conf
-			PG_OLD_IDENT_CONF=${PG_OLD_DATADIR}/pg_ident.conf
-
-			echo -n "  migration in progress. Please be patient..."
-			s6-setuidgid abc pg_upgrade \
+			s6-setuidgid abc initdb \
+				--pgdata="${PG_DATA_DIR}" \
 				--username="${PG_USER}" \
-				--old-datadir="${PG_OLD_DATADIR}" \
-				--new-datadir="${PG_DATA_DIR}" \
-				--old-options="-c config_file=${PG_OLD_CONF} --hba_file=${PG_OLD_HBA_CONF} --ident_file=${PG_OLD_IDENT_CONF}" \
-				--new-options="-c config_file=${PG_CONF} --hba_file=${PG_HBA_CONF} --ident_file=${PG_IDENT_CONF}" >/dev/null
-			echo " [DONE]"
-		fi
-	;;
+				--locale="${LANG}" \
+				--encoding=unicode \
+				--auth=trust ${PG_PASS:+--pwfile=/tmp/pwfile} >/dev/null
+
+			if [[ -n ${PG_OLD_VERSION} ]]; then
+				PG_OLD_DATADIR=${PG_HOME}/${PG_OLD_VERSION}/main
+				PG_OLD_CONF=${PG_OLD_DATADIR}/postgresql.conf
+				PG_OLD_HBA_CONF=${PG_OLD_DATADIR}/pg_hba.conf
+				PG_OLD_IDENT_CONF=${PG_OLD_DATADIR}/pg_ident.conf
+
+				echo -n "  migration in progress. Please be patient..."
+				s6-setuidgid abc pg_upgrade \
+					--username="${PG_USER}" \
+					--old-datadir="${PG_OLD_DATADIR}" \
+					--new-datadir="${PG_DATA_DIR}" \
+					--old-options="-c config_file=${PG_OLD_CONF} --hba_file=${PG_OLD_HBA_CONF} --ident_file=${PG_OLD_IDENT_CONF}" \
+					--new-options="-c config_file=${PG_CONF} --hba_file=${PG_HBA_CONF} --ident_file=${PG_IDENT_CONF}" >/dev/null
+				echo " [DONE]"
+			fi
+		;;
 	esac
 
 	# Configure filesystem journal
diff --git a/rootfs/etc/postgresql/functions b/rootfs/etc/postgresql/functions
--- a/rootfs/etc/postgresql/functions
+++ b/rootfs/etc/postgresql/functions
@@ -2,25 +2,26 @@
 # shellcheck shell=bash disable=SC1008
 set -e
 
-# shellcheck source=env-defaults
-source /etc/postgresql/env-defaults
-
-
-################################################################################
-# Logging
+## Logging
+# $1 message
 log-init() {
 	s6-echo -- "[cont-init.d] ${0##*/}: $1"
 }
 
-################################################################################
 ## Execute command as PG_USER
 exec_as_postgres() {
   sudo -HEu postgres "$@"
 }
 
+## Loading dev-defaults
+log-init "loading env-defaults"
+# shellcheck source=env-defaults
+source /etc/postgresql/env-defaults
 
-################################################################################
-# Set postgresql parameter
+## Set postgresql parameter
+# $1 key
+# $2 value
+# $3 verbosity default:verbose
 set_postgresql_param() {
 	local key=${1}
 	local value=${2}
@@ -43,9 +44,10 @@ set_postgresql_param() {
 	fi
 }
 
-
-################################################################################
-# Set recovery database parameter
+## Set recovery database parameter
+# $1 key
+# $2 value
+# $3 hide value 'true/false'
 set_recovery_param() {
 	local key=${1}
 	local value=${2}
@@ -66,8 +68,8 @@ set_recovery_param() {
 	fi
 }
 
-
-# Set HBA Parameter
+## Set HBA Parameter
+# $1 value to set in hba config
 set_hba_param() {
 	local value=${1}
 
@@ -77,9 +79,7 @@ set_hba_param() {
 	fi
 }
 
-
-################################################################################
-# Check if database is ready for connections
+## Check if database is ready for connections
 is_db_ready() {
 	cmd="pg_isready -h localhost -p 5432 -U ${DB_USER} -d postgres -t 1"
 	timeout=${PG_READY_CONNECT_TIMEOUT}
@@ -98,9 +98,7 @@ is_db_ready() {
 	echo "  [CONNECTED]"
 }
 
-
-################################################################################
-# Check if master is ready for connections
+## Check if master is ready for connections
 is_master_ready() {
 	cmd="pg_isready -h ${REPLICATION_HOST} -p ${REPLICATION_PORT} -U ${REPLICATION_USER} -d postgres -t 1"
 	timeout=${PG_READY_CONNECT_MASTER_TIMEOUT}
@@ -119,13 +117,12 @@ is_master_ready() {
 	echo "  [CONNECTED]"
 }
 
-
-################################################################################
-# Check if enabled
+## Check if enabled
+# $1 parameter to Check
+#
+# usage: if is_enabled "${VAR}"; then
 is_enabled() {
-    local BOOL
-
-    BOOL=${1}
+    local BOOL=${1}
 
     # shellcheck disable=2086
     if (( BOOL == 1 )) || [ ${BOOL} == true ] || [ ${BOOL,,} == "true" ] || [ ${BOOL,,} == "enable" ] || [ ${BOOL,,} == "enabled" ] || [ ${BOOL,,} == "on" ]; then
@@ -135,5 +132,155 @@ is_enabled() {
     return 1
 }
 
+## Set container timezone
+# $1 Timezone
+container_set_timezone() {
+	cp "/usr/share/zoneinfo/${TZ}" /etc/localtime
+	log-init "Timezone set to ${TZ}"
+}
+
+psql_configure_data_dir() {
+	if [ ! -d "${PG_DATA_DIR}" ]; then
+		log-init "creating directory::data [${PG_DATA_DIR}]"
+		mkdir -p "${PG_DATA_DIR}"
+	else
+		log-init "directory::data exists [${PG_DATA_DIR}]"
+	fi
+
+	if [ -d "${PG_DATA_DIR}" ]; then
+		find "${PG_DATA_DIR}" -type f -exec chmod 0600 {} \;
+		find "${PG_DATA_DIR}" -type d -exec chmod 0700 {} \;
+	fi
+
+	# Set permissions on PG_HOME
+	log-init "setting permissions::home"
+	chown -R abc:abc "${PG_HOME}"
+}
+
+psql_configure_log_dir() {
+	if [ ! -d "${PG_LOG_DIR}" ]; then
+		log-init "creating directory::log [${PG_LOG_DIR}]"
+		mkdir -p "${PG_LOG_DIR}"
+	else
+		log-init "directory::log exists [${PG_LOG_DIR}]"
+	fi
+
+	# Set permissions on PG_LOGDIR
+	log-init "setting permissions::log"
+	chmod -R 1775 "${PG_LOG_DIR}"
+	chown -R abc:abc "${PG_LOG_DIR}"
+}
+
+psql_configure_run_dir() {
+	if [ ! -d "${PG_RUN_DIR}" ]; then
+		log-init "creating directory::run [${PG_RUN_DIR}]"
+		mkdir -p "${PG_RUN_DIR}" "${PG_RUN_DIR}/${PG_VERSION}-main.pg_stat_tmp"
+	else
+		log-init "directory::run exists [${PG_RUN_DIR}]"
+	fi
+
+	if [ ! -L /run/postgresql/postgresql ]; then
+		ln -s "${PG_RUN_DIR}" /run/postgresql
+	fi
+
+	# Set Permissions on PG_RUN_DIR
+	log-init "setting permissions::run"
+	chmod -R 0755 "${PG_RUN_DIR}"
+	chmod g+s "${PG_RUN_DIR}"
+	chown -R abc:abc "${PG_RUN_DIR}"
+}
+
+psql_configure_certs_dir() {
+	if [ ! -d "${PG_CERTS_DIR}" ]; then
+		log-init "creating directory::certs [${PG_CERTS_DIR}]"
+		mkdir -p "${PG_CERTS_DIR}"
+	else
+		log-init "directory::certs exists [${PG_CERTS_DIR}]"
+	fi
+
+	# set permissions on PG_CERTS_DIR
+	chown abc:abc "${PG_CERTS_DIR}"
+}
+
+psql_configure_initdb_dir() {
+	if [ ! -d "${PG_INIT_DB}" ]; then
+		log-init "creating directory::init.db.d [${PG_INIT_DB}]"
+		mkdir -p "${PG_INIT_DB}"
+	fi
+
+	# Set permissions on PG_INIT_DB
+	log-init "setting permissions::init.db.d"
+	chown -R abc:abc "${PG_INIT_DB}"
+}
+
+psql_validate_certs() {
+	if is_enabled "${PG_SSL}"; then
+		log-init "SSL/TLS: Enabled"
+
+		if [ ! -f "${PG_CERTS_DIR}/server.crt" ]; then
+			log-init "ERROR: SSL/TLS is enabled certificate not found [${PG_CERTS_DIR}/server.crt]"
+			exit 41
+		else
+			if [ "$(stat -c "%a" "${PG_CERTS_DIR}/server.crt")" != "644" ]; then
+				log-init "invalid permissions for ${PG_CERTS_DIR}/server.crt; expect: 644"
+				exit 42
+			fi
+		fi
+
+		if [ ! -f "${PG_CERTS_DIR}/server.key" ]; then
+			log-init "ERROR: SSL/TLS is enabled certificate key not found [${PG_CERTS_DIR}/server.key]"
+			exit 43
+		else
+			if [ "$(stat -c "%a" "${PG_CERTS_DIR}/server.key")" != "640" ]; then
+				log-init "invalid permissions for ${PG_CERTS_DIR}/server.key; expect: 640"
+				exit 44
+			fi
+		fi
+	fi
+}
+
+psql_validate_replicate_params() {
+	if [[ -z $REPLICATION_HOST ]]; then
+		log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_HOST not set"
+		exit 18
+	fi
+
+	if [[ -z $REPLICATION_USER ]]; then
+		log-init "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_USER not set"
+		exit 19
+	fi
+
+	if [[ -z $REPLICATION_PASS ]]; then
+		echo "ERROR: REPLICATION_MODE=${REPLICATION_MODE^^}; required variable REPLICATION_PASS not set"
+		exit 20
+	fi
+}
+
+psql_validate_pgpass() {
+	if [ "$PG_PASS" == "postgres" ]; then
+		log-init "WARNING: postgres user password still set to default; only use this for test/dev environments"
+	fi
+}
+
+psql_validate_db_user() {
+	if [[ -z ${DB_USER} ]]; then
+		log-init "ERROR: required variable DB_USER not set"
+		exit 15
+	fi
+}
+
+psql_validate_db_pass() {
+	if [[ -z ${DB_PASS} ]]; then
+		log-init "ERROR: required variable DB_PASS not set"
+		exit 16
+	fi
+}
+
+psql_validate_db_name() {
+	if [[ -z ${DB_NAME} ]]; then
+		log-init "ERROR: required variable DB_NAME not set"
+		exit 17
+	fi
+}
 
 # EOF
